CC = gcc

all: binary_heap.c binary_heap.h adjacencyList.c adjacencyList.h dijkstra.c dijkstra.h main_dijkstra.c
	$(CC) -g -Wall -Wextra main_dijkstra.c dijkstra.c binary_heap.c adjacencyList.c

clean: a.out
	rm a.out
